package com.example.examplemod.stage2;

public final class Stage2Constants {
    public static final int GOAT_HORN_SPIKES_QI_COST = 30;
    public static final int GOAT_HORN_SPIKES_COOLDOWN_TICKS = 1000;
    public static final int GOAT_HORN_SPIKES_COUNT = 6;
    public static final float GOAT_HORN_SPIKE_DAMAGE = 4.0F;
    public static final int GOAT_HORN_SPIKE_DRAIN_QI = 8;
    public static final double GOAT_HORN_SPIKE_RANGE = 18.0D;
    public static final float GOAT_HORN_SPIKE_SPEED = 1.4F;
    public static final float GOAT_HORN_SPIKE_INACCURACY = 0.1F;
    public static final float GOAT_HORN_SPIKE_SPREAD_DEGREES = 4.0F;
    public static final int CHOP_QI_COST = 10;
    public static final int CHOP_COOLDOWN_TICKS = 10;
    public static final float CHOP_DAMAGE = 2.0F;
    public static final double CHOP_RANGE = 3.5D;
    public static final double BUTCHER_CHOP_RANGE = 3.8D;
    public static final double CHOP_VERTICAL_RANGE = 2.8D;
    public static final double CHOP_HALF_ANGLE_DEGREES = 45.0D;
    public static final double CHOP_HALF_ANGLE_COS = 0.70710678D;
    public static final double CHOP_KNOCKBACK = 0.3D;
    public static final double BUTCHER_CHOP_KNOCKBACK = 0.75D;
    public static final int CHOP_GOAT_HORN_DISABLE_TICKS = 200;
    public static final int BUTCHER_CHOP_WINDUP_TICKS = 14;
    public static final int BUTCHER_CHOP_COOLDOWN_MIN_TICKS = 70;
    public static final int BUTCHER_CHOP_COOLDOWN_RANDOM_TICKS = 41;
    public static final float BUTCHER_CHOP_DAMAGE = 5.0F;
    public static final int BUTCHER_RANGED_COOLDOWN_MIN_TICKS = 45;
    public static final int BUTCHER_RANGED_COOLDOWN_RANDOM_TICKS = 36;
    public static final float BUTCHER_RANGED_DAMAGE = 3.0F;
    public static final double BUTCHER_RANGED_RANGE = 14.0D;
    public static final int BUTCHER_RANGED_DRAIN_QI = 8;
    public static final int BUTCHER_RANGED_SLOW_TICKS = 20;
    public static final float BUTCHER_RANGED_SPEED = 1.25F;
    public static final int SOUL_LAMP_RADIUS = 7;
    public static final int SOUL_LAMP_CHECK_INTERVAL = 10;
    public static final int SOUL_LAMP_LIGHT_LEVEL = 12;
    public static final int SOUL_LAMP_ACTIVE_TICKS = 400;
    public static final float WRAITH_HEALTH = 26.0F;
    public static final float WRAITH_DAMAGE = 4.0F;
    public static final int WRAITH_MAX_QI = 80;
    public static final double WRAITH_SPEED = 0.30D;
    public static final double WRAITH_FOLLOW_RANGE = 24.0D;
    public static final float WRAITH_UNMANIFESTED_DAMAGE_MULTIPLIER = 0.0F;
    public static final double WRAITH_MANIFESTED_SPEED_MULTIPLIER = 0.85D;
    public static final float WRAITH_LIGHTWAVE_DAMAGE_MULTIPLIER = 1.5F;
    public static final int WRAITH_RANGED_COOLDOWN_MIN_TICKS = 45;
    public static final int WRAITH_RANGED_COOLDOWN_RANDOM_TICKS = 31;
    public static final float WRAITH_RANGED_DAMAGE = 3.0F;
    public static final double WRAITH_RANGED_RANGE = 13.0D;
    public static final int WRAITH_RANGED_DRAIN_QI = 5;
    public static final int WRAITH_RANGED_SLOW_TICKS = 25;
    public static final float WRAITH_RANGED_SPEED = 1.05F;
    public static final int TRIANGLE_DISABLE_TICKS_BY_LIGHTWAVE = 160;
    public static final int TRIANGLE_TRAP_SLOW_DURATION = 40;
    public static final int TRIANGLE_TRAP_SLOW_AMPLIFIER = 1;
    public static final int TRIANGLE_TRAP_QI_DRAIN = 2;
    public static final int TRIANGLE_TRAP_TRIGGER_COOLDOWN = 20;
    public static final int SEVEN_SCATTERED_STRIKES_QI_COST = 8;
    public static final int SEVEN_SCATTERED_STRIKES_COOLDOWN_TICKS = 200;
    public static final int SEVEN_SCATTERED_STRIKES_PROJECTILE_COUNT = 8;
    public static final float SEVEN_SCATTERED_STRIKES_DAMAGE = 2.5F;
    public static final int SEVEN_SCATTERED_STRIKES_QI_DAMAGE = 3;
    public static final double SEVEN_SCATTERED_STRIKES_RANGE = 14.0D;
    public static final float SEVEN_SCATTERED_STRIKES_SPEED = 1.45F;
    public static final float SEVEN_SCATTERED_STRIKES_INACCURACY = 0.18F;
    public static final float SEVEN_SCATTERED_STRIKES_SPREAD_DEGREES = 15.0F;

    private Stage2Constants() {
    }
}
